--gan quyen chi nhanh 1
CREATE USER TS01 IDENTIFIED BY TS01;
GRANT CONNECT, DBA TO TS01;

CREATE USER giamdoc IDENTIFIED BY giamdoc; 
CREATE USER quanly IDENTIFIED BY quanly; 
CREATE USER nhanvien IDENTIFIED BY nhanvien;
GRANT CONNECT, DBA TO TS01; 
GRANT CREATE PUBLIC DATABASE LINK TO TS01;
GRANT CONNECT, DBA TO giamdoc;
GRANT CREATE PUBLIC DATABASE LINK TO giamdoc; 
GRANT CONNECT, DBA TO quanly; 
GRANT CREATE PUBLIC DATABASE LINK TO quanly;
GRANT CONNECT, DBA TO nhanvien; 
GRANT CREATE PUBLIC DATABASE LINK TO nhanvien;
GRANT CONNECT, DBA TO TS02; 
GRANT CREATE PUBLIC DATABASE LINK TO TS01;
GRANT CONNECT, DBA TO giamdoc;
GRANT CREATE PUBLIC DATABASE LINK TO giamdoc; 
GRANT CONNECT, DBA TO quanly; 
GRANT CREATE PUBLIC DATABASE LINK TO quanly;
GRANT CONNECT, DBA TO nhanvien; 
GRANT CREATE PUBLIC DATABASE LINK TO nhanvien;
GRANT CONNECT, DBA TO giamdoc;
GRANT CREATE SESSION, SYSDBA TO giamdoc;
GRANT SELECT ON TS01.SANPHAM TO giamdoc; 
GRANT SELECT ON TS01.CHINHANH TO giamdoc; 
GRANT SELECT ON TS01.NV_SANPHAM TO giamdoc; 
GRANT SELECT ON TS01.QL_SANPHAM TO giamdoc; 
GRANT SELECT ON TS01.KHACHHANG TO giamdoc;
GRANT SELECT ON TS01.HOADON TO giamdoc;
GRANT SELECT ON TS01.CTHD TO giamdoc;
GRANT SELECT ON TS01.NHACUNGCAP TO giamdoc;

GRANT SELECT ON TS01.SANPHAM TO quanly; 
GRANT SELECT ON TS01.CHINHANH TO quanly; 
GRANT SELECT ON TS01.QL_SANPHAM TO quanly; 
GRANT SELECT ON TS01.KHACHHANG TO quanly; 
GRANT SELECT ON TS01.HOADON TO quanly; 
GRANT SELECT ON TS01.CTHD TO quanly; 

GRANT SELECT ON TS01.SANPHAM TO nhanvien; 
GRANT SELECT ON TS01.CHINHANH TO nhanvien; 
GRANT SELECT ON TS01.NV_SANPHAM TO nhanvien; 
GRANT SELECT ON TS01.KHACHHANG TO nhanvien; 
GRANT SELECT ON TS01.HOADON TO nhanvien; 
GRANT SELECT ON TS01.CTHD TO nhanvien;


---gan quyen 2
CREATE USER TS02 IDENTIFIED BY TS02;
GRANT CONNECT, DBA TO TS02;

GRANT SELECT ON TS02.SANPHAM TO giamdoc; 
GRANT SELECT ON TS02.CHINHANH TO giamdoc; 
GRANT SELECT ON TS02.NV_SANPHAM TO giamdoc; 
GRANT SELECT ON TS02.QL_SANPHAM TO giamdoc; 
GRANT SELECT ON TS02.KHACHHANG TO giamdoc;
GRANT SELECT ON TS02.HOADON TO giamdoc;
GRANT SELECT ON TS02.CTHD TO giamdoc;
GRANT SELECT ON TS02.NHACUNGCAP TO giamdoc;

GRANT SELECT ON TS02.SANPHAM TO quanly; 
GRANT SELECT ON TS02.CHINHANH TO quanly; 
GRANT SELECT ON TS02.QL_SANPHAM TO quanly; 
GRANT SELECT ON TS02.KHACHHANG TO quanly; 
GRANT SELECT ON TS02.HOADON TO quanly; 
GRANT SELECT ON TS02.CTHD TO quanly; 

GRANT SELECT ON TS02.SANPHAM TO nhanvien; 
GRANT SELECT ON TS02.CHINHANH TO nhanvien; 
GRANT SELECT ON TS02.NV_SANPHAM TO nhanvien; 
GRANT SELECT ON TS02.KHACHHANG TO nhanvien; 
GRANT SELECT ON TS02.HOADON TO nhanvien; 
GRANT SELECT ON TS02.CTHD TO nhanvien;

-- tao database link
CREATE PUBLIC DATABASE LINK TS02_dblink connect to giamdoc identified by giamdoc using 'TS02_link';
CREATE PUBLIC DATABASE LINK TS01_dblink connect to giamdoc identified by giamdoc using 'TS01_link';
